### ISSUE TITLE
Add Api URLs for testing environments

### ISSUE THREAD

**Issue by nbodesa** [sourceallies/aws-oauth-1.0-proxy#56]
Currently there is only one API Url and it's pointed at production.

It would be nice to have Dev and Qual versions as well to be able to test changes against before production deployment.

**Comment by nbodesa** [comment]
Turns out we already do have different environments for Dev/Qual/Prod in the cloudformation.template.yml

There's an entry at the bottom like so:

```yaml
Outputs:
  ApiURL:
    Description: API endpoint for the lambdas
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ 
```
While it says `/Prod` at the end the magical ${ServerlessRestApi} is different in dev/qual/prod.

You can find the value of this by logging into the AWS Dev/Qual/Prod account and going to Cloudformation > aws-oauth-proxy > Outputs. There you can see the full value of ApiUrl.
